/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.birthday.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Birthday service. Represents a row in the &quot;Sample_Birthday_Birthday&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.birthday.model.impl.BirthdayModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.birthday.model.impl.BirthdayImpl}.
 * </p>
 *
 * @author Ryan Park
 * @see Birthday
 * @see com.liferay.sample.birthday.model.impl.BirthdayImpl
 * @see com.liferay.sample.birthday.model.impl.BirthdayModelImpl
 * @generated
 */
@ProviderType
public interface BirthdayModel extends BaseModel<Birthday> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a birthday model instance should use the {@link Birthday} interface instead.
	 */

	/**
	 * Returns the primary key of this birthday.
	 *
	 * @return the primary key of this birthday
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this birthday.
	 *
	 * @param primaryKey the primary key of this birthday
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the birthday ID of this birthday.
	 *
	 * @return the birthday ID of this birthday
	 */
	public long getBirthdayId();

	/**
	 * Sets the birthday ID of this birthday.
	 *
	 * @param birthdayId the birthday ID of this birthday
	 */
	public void setBirthdayId(long birthdayId);

	/**
	 * Returns the name of this birthday.
	 *
	 * @return the name of this birthday
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this birthday.
	 *
	 * @param name the name of this birthday
	 */
	public void setName(String name);

	/**
	 * Returns the date of this birthday.
	 *
	 * @return the date of this birthday
	 */
	public Date getDate();

	/**
	 * Sets the date of this birthday.
	 *
	 * @param date the date of this birthday
	 */
	public void setDate(Date date);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.sample.birthday.model.Birthday birthday);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.sample.birthday.model.Birthday> toCacheModel();

	@Override
	public com.liferay.sample.birthday.model.Birthday toEscapedModel();

	@Override
	public com.liferay.sample.birthday.model.Birthday toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}